package thread

import (
	"encoding/base64"
	"encoding/json"
	"faryne.dev/service/chrome_helper"
	"fmt"
	"github.com/chromedp/chromedp"
	"github.com/skip2/go-qrcode"
	"io"
	"net/http"
	"net/url"
	"time"
)

type OembedThread struct {
	Html         string `json:"html"`
	ProviderName string `json:"provider_name"`
	ProviderUrl  string `json:"provider_url"`
	Type         string `json:"type"`
	Version      string `json:"version"`
	Width        int64  `json:"width"`
}

var oembedHtml = `
		<!DOCTYPE html>
		<html>
		<head>
			<meta charset="UTF-8">
			<style>
				body { 
					margin: 0; 
					display: flex; 
					padding: 0;
					justify-content: center; 
					background: transparent; 
				}
				/* 3. 核心：強制撐開 Threads 產生的 iframe */
				iframe {
					width: 500px !important;
					max-width: none !important;
				}

				.footer {
					display: flex;
					justify-content: space-between;
					align-items: center;
					margin-top: 25px;
					padding: 15px 20px;
					border-top: 1px solid #f0f0f0; /* 加入一條淺淺的分隔線 */
				}
				/* 左側：工具宣傳 */
				.brand-info {
					display: flex;
					flex-direction: column;
				}
				.brand-name {
					font-size: 16px;
					font-weight: 700;
					color: #1e1e1e;
					margin-bottom: 4px;
				}
				.brand-slogan {
					font-size: 12px;
					color: #999;
					letter-spacing: 0.5px;
				}
		
				/* 右側：QR Code 區域 */
				.qr-section {
					display: flex;
					align-items: center;
					gap: 12px;
				}
				.qr-text {
					font-size: 11px;
					color: #bbb;
					text-align: right;
					line-height: 1.4;
				}
				.qr-code {
					width: 70px;
					height: 70px;
					border: 1px solid #eee;
					padding: 4px;
					border-radius: 8px;
				}
			</style>
		</head>
		<body>
			<div id="capture-result" style="width: 500px; clear: both">
				%s
				<div class="footer">
					<div class="brand-info">
						<div class="brand-name">Threads Snap</div>
						<div class="brand-slogan">Generated by faryne.dev</div>
					</div>
					
					<div class="qr-section">
						<div class="qr-text">掃描 QR Code<br>開啟原始貼文</div>
						<img class="qr-code" src="data:image/png;base64,%s" />
					</div>
				</div>
			</div>
		</body>
		</html>
	`

func OEmbedCapture(uri string) (string, error) {
	cleanUri, _ := url.Parse(uri)
	cleanUri.RawQuery = ""
	uri = cleanUri.String()
	newUri := "https://graph.threads.net/v1.0/oembed?" + url.Values{"url": {uri}}.Encode()
	if uri == "" || uri[0] != 'h' {
		return "", fmt.Errorf("uri is not matched: %s", uri)
	}
	resp, err := http.DefaultClient.Get(newUri)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	content, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	var t OembedThread
	if unmarshalError := json.Unmarshal(content, &t); unmarshalError != nil {
		return "", err
	}
	if t.Html == "" {
		return "", fmt.Errorf("html is empty, cannot capture oembed html")
	}

	// 先產生 qr code
	var png []byte
	png, err = qrcode.Encode(uri, qrcode.Medium, 256)
	if err != nil {
		return "", err
	}
	pngB64Str := base64.StdEncoding.EncodeToString(png)

	// 開始截圖
	var buf []byte
	chromeDpInstance := chrome_helper.NewDefaultInstance()
	dataUri := fmt.Sprintf("data:text/html;charset=utf-8,%s", url.PathEscape(fmt.Sprintf(oembedHtml, t.Html, pngB64Str)))
	if len(chromeDpInstance.Cancels) > 0 {
		for _, v := range chromeDpInstance.Cancels {
			defer v()
		}
	}
	var x, y, width, height float64

	chromeDpError := chromedp.Run(
		chromeDpInstance.Ctx,
		chromedp.EmulateViewport(550, 700),
		chromedp.Navigate(dataUri),
		chromedp.WaitVisible(`#capture-result`, chromedp.ByQuery),
		chromedp.WaitReady(`iframe`, chromedp.ByQuery),
		chromedp.Sleep(3*time.Second),
		chromedp.Evaluate(`
        (function() {
            const el = document.getElementById('capture-result');
            const rect = el.getBoundingClientRect();
            return {
                x: rect.left,
                y: rect.top,
                width: rect.width,
                height: rect.height
            };
        })()
    `, &struct {
			X      float64 `json:"x"`
			Y      float64 `json:"y"`
			Width  float64 `json:"width"`
			Height float64 `json:"height"`
		}{x, y, width, height}),
		chromedp.FullScreenshot(&buf, 100),
		//chromedp.Screenshot(`#capture-result`, &buf, chromedp.ByID),
	)
	if chromeDpError != nil {
		return "", chromeDpError
	}

	str := base64.StdEncoding.EncodeToString(buf)
	return str, nil

}
