version: "3.6"

services:
  mysql:
    image: arm64v8/mysql
    container_name: mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: "lab"
#  redis:
#    image: redis:latest
  manticore:
    image: manticoresearch/manticore
    container_name: search
    ports:
      - "9306:9306"
      - "9308:9308"
      - "9312:9312"
