package route

import (
	"faryne.dev/config"
	"faryne.dev/controller/auth"
	"faryne.dev/controller/storyteller"
	"faryne.dev/controller/storytelleroauth"
	"faryne.dev/middleware/authsession"
	storytellerAI "faryne.dev/middleware/storytellerai"
	storytellerAudit "faryne.dev/middleware/storytelleraudit"
	authService "faryne.dev/service/auth"
	"github.com/gofiber/fiber/v3"
)

func Storyteller(app *fiber.App) {
	group := app.Group("/storyteller")
	group.Get("/search", storyteller.SearchWorks)
	group.Get("/search/projects", storyteller.SearchProjectsGrouped)
	group.Get("/projects/public", storyteller.PublicProjects)
	group.Get("/user/:username", storyteller.PublicUserProjects)
	group.Get("/user/:username/favorites/projects", storyteller.PublicFavoriteProjects)
	group.Get("/user/:username/favorites/authors", storyteller.PublicFavoriteAuthors)
	// 作者動態：公開讀取（帶登入 header 時多回按讚、能否留言等狀態）；要註冊在 authenticated 群組之前
	group.Get("/user/:username/posts", storyteller.PublicAuthorPosts)
	group.Get("/posts/:post", storyteller.PublicAuthorPost)
	// 專案討論版：公開讀取（不公開作品帶 ?share=）
	group.Get("/story/:project/discussions", storyteller.PublicDiscussionThreads)
	group.Get("/discussions/:thread", storyteller.PublicDiscussionThread)
	group.Get("/story/share/:token", storyteller.SharedProject)
	group.Get("/story/:project", storyteller.PublicProject)
	group.Get("/story/:project/stories/:story/latest-version", storyteller.PublicStoryLatestVersion)
	group.Get("/story/:project/stories/:story/versions", storyteller.PublicStoryVersions)
	group.Get("/story/:project/stories/:story/image-pages", storyteller.PublicImageStoryPages)
	group.Get("/story/share/:token/stories/:story/image-pages", storyteller.SharedImageStoryPages)
	// OAuth 授權頁在登入前就要顯示 client 資訊，所以 preview 不需要 session
	group.Get("/oauth/authorize/preview", storytelleroauth.AuthorizePreview)
	group.Post("/auth/session", storytellerAudit.WebSuccess(), storyteller.CreateSession)
	group.Delete("/auth/session", authsession.Optional(authService.BrandStoryteller), storytellerAudit.WebSuccess(), auth.DestroySessionBestEffort)
	if config.EnvConfig().EnableDevAuthBypass {
		group.Post("/auth/dev-session", storyteller.CreateDevSession)
	}

	authenticated := group.Group("", authsession.New(authService.BrandStoryteller), storytellerAudit.WebSuccess())
	// 站內 AI 助理（agent chat、API key、Skill、用量、記憶草稿、AI 提案）的路由逐條掛 aiGate；
	// 不能用空前綴 group 包住——Fiber 的 group middleware 會套到之後註冊的所有路由。
	aiGate := storytellerAI.Gate()
	// sliding TTL 續期用（前端 touchAuthSession），純粹靠這個 group 的 brand 檢查生效，
	// handler 本身跟主站共用（無狀態、只回 active:true，不用另外寫一份）。
	authenticated.Get("/auth/session", auth.GetSession)
	authenticated.Get("/user", storyteller.UserProfile)
	authenticated.Post("/user", storyteller.SaveUserProfile)
	authenticated.Put("/user", storyteller.SaveUserProfile)
	authenticated.Delete("/user", storyteller.DeleteUserProfile)
	authenticated.Get("/profiles", storyteller.AuthorProfiles)
	authenticated.Post("/profiles", storyteller.CreateAuthorProfile)
	authenticated.Put("/profiles/:profile", storyteller.UpdateAuthorProfile)
	authenticated.Delete("/profiles/:profile", storyteller.DeleteAuthorProfile)
	authenticated.Get("/limits", storyteller.AccountLimits)
	authenticated.Get("/projects", storyteller.Projects)
	authenticated.Post("/projects", storyteller.CreateProject)
	authenticated.Get("/favorites", storyteller.FavoriteProjects)
	authenticated.Get("/favorites/authors", storyteller.FavoriteAuthors)
	authenticated.Get("/authors/:author/favorite", storyteller.AuthorFavoriteStatus)
	authenticated.Post("/authors/:author/favorite", storyteller.CreateAuthorFavorite)
	authenticated.Delete("/authors/:author/favorite", storyteller.DeleteAuthorFavorite)
	authenticated.Get("/projects/:project", storyteller.Project)
	authenticated.Get("/projects/:project/search", storyteller.WorkspaceSearch)
	authenticated.Get("/projects/:project/memories/manage", storyteller.ManageAssistantMemories)
	authenticated.Put("/projects/:project/memories/:memory", storyteller.UpdateAssistantMemory)
	authenticated.Delete("/memories/:memory", storyteller.DeleteAssistantMemory)
	authenticated.Put("/projects/:project", storyteller.UpdateProject)
	authenticated.Delete("/projects/:project", storyteller.DeleteProject)
	authenticated.Get("/projects/:project/favorite", storyteller.FavoriteStatus)
	authenticated.Post("/projects/:project/favorite", storyteller.CreateFavorite)
	authenticated.Delete("/projects/:project/favorite", storyteller.DeleteFavorite)
	authenticated.Patch("/favorites/projects/:project/visibility", storyteller.SetFavoriteProjectVisibility)
	authenticated.Patch("/favorites/authors/:author/visibility", storyteller.SetFavoriteAuthorVisibility)
	authenticated.Get("/projects/:project/ranking", storyteller.RankingStatus)
	authenticated.Put("/projects/:project/ranking", storyteller.SaveRanking)
	authenticated.Delete("/projects/:project/ranking", storyteller.DeleteRanking)
	authenticated.Get("/story/:project/bookmarks", storyteller.ProjectStoryBookmarks)
	authenticated.Get("/story/:project/stories/:story/bookmarks", storyteller.StoryBookmarks)
	authenticated.Post("/story/:project/stories/:story/bookmarks", storyteller.CreateStoryBookmark)
	authenticated.Delete("/story/:project/stories/:story/bookmarks", storyteller.DeleteStoryBookmark)
	authenticated.Get("/story/:project/reading-records", storyteller.ReadingRecords)
	authenticated.Put("/story/:project/reading-records", storyteller.SaveReadingRecords)

	// 作者動態：發文身份由 :username 決定（必須是自己的身份），留言身份由後端判定
	authenticated.Post("/user/:username/posts", storyteller.CreateAuthorPost)
	authenticated.Get("/user/:username/attachable-works", storyteller.AttachableWorks)
	authenticated.Delete("/posts/:post", storyteller.DeleteAuthorPost)
	authenticated.Put("/posts/:post/pin", storyteller.PinAuthorPost)
	authenticated.Delete("/posts/:post/pin", storyteller.UnpinAuthorPost)
	authenticated.Put("/posts/:post/like", storyteller.LikeAuthorPost)
	authenticated.Delete("/posts/:post/like", storyteller.UnlikeAuthorPost)
	authenticated.Post("/posts/:post/comments", storyteller.CreateComment)
	authenticated.Delete("/comments/:comment", storyteller.DeleteComment)
	authenticated.Post("/comments/:comment/block", storyteller.BlockCommenter)
	authenticated.Put("/comments/:comment", storyteller.EditComment)
	authenticated.Get("/blocks", storyteller.AuthorBlocks)
	authenticated.Delete("/blocks/:block", storyteller.DeleteAuthorBlock)

	// 專案討論版：發言身份由後端判定（作者可帶 as 選作品署名身份），不公開作品帶 ?share=
	authenticated.Post("/story/:project/discussions", storyteller.CreateDiscussionThread)
	authenticated.Put("/discussions/:thread", storyteller.EditDiscussionThread)
	authenticated.Delete("/discussions/:thread", storyteller.DeleteDiscussionThread)
	authenticated.Put("/discussions/:thread/lock", storyteller.LockDiscussionThread)
	authenticated.Delete("/discussions/:thread/lock", storyteller.UnlockDiscussionThread)
	authenticated.Post("/discussions/:thread/block", storyteller.BlockDiscussionStarter)
	authenticated.Post("/discussions/:thread/comments", storyteller.CreateDiscussionComment)

	authenticated.Post("/oauth/authorize", storytelleroauth.Authorize)
	authenticated.Get("/oauth/grants", storytelleroauth.Grants)
	authenticated.Delete("/oauth/grants/:grant", storytelleroauth.RevokeGrant)

	authenticated.Get("/provider-apikeys", aiGate, storyteller.ProviderAPIKeys)
	authenticated.Post("/provider-apikeys", aiGate, storyteller.CreateProviderAPIKey)
	authenticated.Put("/provider-apikeys/:apikey", aiGate, storyteller.UpdateProviderAPIKey)
	authenticated.Delete("/provider-apikeys/:apikey", aiGate, storyteller.DeleteProviderAPIKey)
	authenticated.Get("/provider-apikeys/:apikey/models", aiGate, storyteller.ProviderAPIKeyModels)
	authenticated.Post("/provider-apikeys/:apikey/models", aiGate, storyteller.CreateProviderAPIKeyModel)
	authenticated.Delete("/provider-apikeys/:apikey/models/:model", aiGate, storyteller.DeleteProviderAPIKeyModel)
	authenticated.Post("/provider-apikeys/:apikey/test-connection", aiGate, storyteller.TestProviderAPIKey)

	authenticated.Get("/account/audit-events", storyteller.AccountAuditEvents)
	authenticated.Get("/account/audit-event-filters", storyteller.AccountAuditEventFilters)
	authenticated.Get("/account/audit-archive-months", storyteller.AuditArchiveMonths)
	authenticated.Post("/account/audit-archive-queries", storyteller.CreateAuditArchiveQuery)
	authenticated.Get("/audit-archive-queries/:query", storyteller.AuditArchiveQueryStatus)
	authenticated.Get("/audit-archive-queries/:query/results", storyteller.AuditArchiveQueryResults)
	authenticated.Get("/personal-access-tokens", storyteller.PersonalAccessTokens)
	authenticated.Post("/personal-access-tokens", storyteller.CreatePersonalAccessToken)
	authenticated.Delete("/personal-access-tokens/:token", storyteller.DeletePersonalAccessToken)

	// 站內通知：unread-count 要排在 :notification 之前，避免被當成 public_id
	authenticated.Get("/notifications", storyteller.Notifications)
	authenticated.Get("/notification-kinds", storyteller.NotificationKinds)
	authenticated.Get("/notifications/unread-count", storyteller.NotificationUnreadCount)
	authenticated.Post("/notifications/read-all", storyteller.ReadAllNotifications)
	authenticated.Get("/notifications/:notification", storyteller.Notification)
	authenticated.Post("/notifications/:notification/read", storyteller.ReadNotification)
	authenticated.Post("/notifications/:notification/lock", storyteller.LockNotification)
	authenticated.Delete("/notifications/:notification/lock", storyteller.UnlockNotification)
	authenticated.Delete("/notifications/:notification", storyteller.DeleteNotification)
	authenticated.Post("/notifications/:notification/follow-back", storyteller.FollowBackNotification)

	authenticated.Get("/usage/summary", aiGate, storyteller.AgentUsageSummary)
	authenticated.Get("/usage/logs", aiGate, storyteller.AgentUsageLogs)

	authenticated.Get("/agents", aiGate, storyteller.Agents)
	authenticated.Get("/agents/provider-models", aiGate, storyteller.AgentProviderModels)
	authenticated.Post("/agents", aiGate, storyteller.CreateAgent)
	authenticated.Get("/agents/:agent", aiGate, storyteller.Agent)
	authenticated.Get("/agents/:agent/versions", aiGate, storyteller.AgentPromptVersions)
	authenticated.Get("/agents/:agent/versions/:version", aiGate, storyteller.AgentPromptVersion)
	authenticated.Put("/agents/:agent", aiGate, storyteller.UpdateAgent)
	authenticated.Delete("/agents/:agent", aiGate, storyteller.DeleteAgent)
	// AI 助理對話：唯一的一組路由，目標（專案／故事／設定集）由請求體指定，不分 story／lore 兩套。
	authenticated.Post("/agent-chats", aiGate, storyteller.SubmitAgent)
	authenticated.Post("/agent-chats/:chat/resend", aiGate, storyteller.ResubmitAgent)
	authenticated.Get("/agent-chats/:chat", aiGate, storyteller.AgentChat)
	authenticated.Post("/agent-chats/:chat/memory-drafts", aiGate, storyteller.GenerateAssistantMemoryDraft)
	authenticated.Get("/memory-drafts/:memory", aiGate, storyteller.AssistantMemoryDraft)
	authenticated.Post("/memory-drafts/:memory/retry", aiGate, storyteller.RetryAssistantMemoryDraft)
	authenticated.Post("/memory-drafts/:memory/confirm", aiGate, storyteller.ConfirmAssistantMemoryDraft)
	authenticated.Delete("/memory-drafts/:memory", aiGate, storyteller.DeleteAssistantMemoryDraft)

	authenticated.Get("/projects/:project/stories", storyteller.Stories)
	authenticated.Post("/projects/:project/stories", storyteller.CreateStory)
	authenticated.Get("/projects/:project/stories/:story", storyteller.Story)
	authenticated.Put("/projects/:project/stories/:story", storyteller.UpdateStory)
	authenticated.Delete("/projects/:project/stories/:story", storyteller.DeleteStory)
	authenticated.Get("/projects/:project/stories/:story/chat-messages/:message/reference-content", aiGate, storyteller.StoryChatMessageReferenceContent)
	authenticated.Get("/projects/:project/agentic-proposals/:proposal/reference-content", aiGate, storyteller.AgentProposalReferenceContent)
	authenticated.Post("/projects/:project/agentic-proposals/:proposal/preview", aiGate, storyteller.PreviewAgentProposal)
	authenticated.Post("/projects/:project/agentic-proposals/:proposal/apply", aiGate, storyteller.ApplyAgentProposal)
	authenticated.Post("/projects/:project/agentic-proposals/:proposal/mark-applied", aiGate, storyteller.MarkAgentProposalApplied)
	authenticated.Post("/projects/:project/agentic-proposals/:proposal/reset", aiGate, storyteller.ResetAgentProposal)
	authenticated.Post("/projects/:project/agentic-proposals/:proposal/reject", aiGate, storyteller.RejectAgentProposal)
	authenticated.Get("/projects/:project/stories/:story/chat-messages", aiGate, storyteller.StoryChatMessages)
	authenticated.Get("/projects/:project/stories/:story/versions", storyteller.StoryVersions)
	authenticated.Get("/projects/:project/stories/:story/versions/:version", storyteller.StoryVersion)
	authenticated.Post("/projects/:project/stories/:story/versions/:version/revert", storyteller.RevertStoryVersion)
	authenticated.Get("/projects/:project/stories/:story/image-pages", storyteller.ImageStoryPages)
	authenticated.Get("/projects/:project/stories/:story/bookmarks", storyteller.StoryWritingBookmarks)
	authenticated.Post("/projects/:project/stories/:story/bookmarks", storyteller.CreateStoryWritingBookmark)
	authenticated.Put("/projects/:project/stories/:story/bookmarks", storyteller.UpdateStoryWritingBookmark)
	authenticated.Delete("/projects/:project/stories/:story/bookmarks", storyteller.DeleteStoryWritingBookmark)

	authenticated.Get("/projects/:project/volumes", storyteller.Volumes)
	authenticated.Post("/projects/:project/volumes", storyteller.CreateVolume)
	authenticated.Put("/projects/:project/volumes/:volume", storyteller.UpdateVolume)
	authenticated.Get("/projects/:project/volumes/:volume/activity", storyteller.VolumeActivity)
	// 冊本身也是一筆 story，刪除沿用既有的 DELETE /projects/:project/stories/:story，
	// 非空檢查在 Service.DeleteStory 裡做，不需要另外開一條刪除路由。

	authenticated.Post("/projects/:project/image-pages/presign", storyteller.PresignImageUpload)

	authenticated.Get("/projects/:project/assets", storyteller.Assets)
	authenticated.Post("/projects/:project/assets/presign", storyteller.PresignAssetUpload)
	authenticated.Post("/projects/:project/assets/confirm", storyteller.ConfirmAssetUpload)
	authenticated.Get("/projects/:project/asset-collections", storyteller.AssetCollections)
	authenticated.Post("/projects/:project/asset-collections", storyteller.CreateAssetCollection)
	authenticated.Put("/projects/:project/asset-collections/:collection", storyteller.UpdateAssetCollection)
	authenticated.Delete("/projects/:project/asset-collections/:collection", storyteller.DeleteAssetCollection)
	authenticated.Get("/projects/:project/assets/:asset", storyteller.Asset)
	authenticated.Post("/projects/:project/assets/:asset/replace/presign", storyteller.PresignAssetReplace)
	authenticated.Post("/projects/:project/assets/:asset/replace/confirm", storyteller.ConfirmAssetReplace)
	authenticated.Put("/projects/:project/assets/:asset", storyteller.UpdateAsset)
	authenticated.Put("/projects/:project/assets/:asset/move", storyteller.MoveAsset)
	authenticated.Delete("/projects/:project/assets/:asset", storyteller.DeleteAsset)

	authenticated.Get("/projects/:project/lores", storyteller.Lores)
	authenticated.Get("/projects/:project/lores/page", storyteller.LoresPage)
	authenticated.Get("/projects/:project/lore-collections", storyteller.LoreCollections)
	authenticated.Post("/projects/:project/lore-collections", storyteller.CreateLoreCollection)
	authenticated.Put("/projects/:project/lore-collections/:collection", storyteller.UpdateLoreCollection)
	authenticated.Delete("/projects/:project/lore-collections/:collection", storyteller.DeleteLoreCollection)
	authenticated.Post("/projects/:project/lores", storyteller.CreateLore)
	authenticated.Get("/projects/:project/lores/:lore", storyteller.Lore)
	authenticated.Put("/projects/:project/lores/:lore", storyteller.UpdateLore)
	authenticated.Put("/projects/:project/lores/:lore/move", storyteller.MoveLore)
	authenticated.Delete("/projects/:project/lores/:lore", storyteller.DeleteLore)
	authenticated.Get("/projects/:project/lores/:lore/chat-messages/:message/reference-content", aiGate, storyteller.LoreChatMessageReferenceContent)
	authenticated.Get("/projects/:project/lores/:lore/chat-messages", aiGate, storyteller.LoreChatMessages)
	authenticated.Get("/projects/:project/lores/:lore/versions", storyteller.LoreVersions)
	authenticated.Get("/projects/:project/lores/:lore/versions/:version", storyteller.LoreVersion)
	authenticated.Post("/projects/:project/lores/:lore/versions/:version/revert", storyteller.RevertLoreVersion)
	authenticated.Get("/projects/:project/lores/:lore/bookmarks", storyteller.LoreWritingBookmarks)
	authenticated.Post("/projects/:project/lores/:lore/bookmarks", storyteller.CreateLoreWritingBookmark)
	authenticated.Put("/projects/:project/lores/:lore/bookmarks", storyteller.UpdateLoreWritingBookmark)
	authenticated.Delete("/projects/:project/lores/:lore/bookmarks", storyteller.DeleteLoreWritingBookmark)
}
