package route

import (
	"faryne.dev/controller/storyteller"
	"faryne.dev/middleware/authsession"
	"github.com/gofiber/fiber/v3"
)

func Storyteller(app *fiber.App) {
	group := app.Group("/storyteller")
	group.Get("/search", storyteller.SearchWorks)
	group.Get("/search/projects", storyteller.SearchProjectsGrouped)
	group.Get("/projects/public", storyteller.PublicProjects)
	group.Get("/user/:username", storyteller.PublicUserProjects)
	group.Get("/user/:username/favorites/projects", storyteller.PublicFavoriteProjects)
	group.Get("/user/:username/favorites/authors", storyteller.PublicFavoriteAuthors)
	group.Get("/story/share/:token", storyteller.SharedProject)
	group.Get("/story/:project", storyteller.PublicProject)
	group.Get("/story/:project/stories/:story/latest-version", storyteller.PublicStoryLatestVersion)
	group.Get("/story/:project/stories/:story/versions", storyteller.PublicStoryVersions)
	group.Get("/story/:project/stories/:story/image-pages", storyteller.PublicImageStoryPages)
	group.Get("/story/share/:token/stories/:story/image-pages", storyteller.SharedImageStoryPages)

	authenticated := group.Group("", authsession.New())
	authenticated.Get("/user", storyteller.UserProfile)
	authenticated.Post("/user", storyteller.SaveUserProfile)
	authenticated.Put("/user", storyteller.SaveUserProfile)
	authenticated.Delete("/user", storyteller.DeleteUserProfile)
	authenticated.Get("/projects", storyteller.Projects)
	authenticated.Post("/projects", storyteller.CreateProject)
	authenticated.Get("/favorites", storyteller.FavoriteProjects)
	authenticated.Get("/favorites/authors", storyteller.FavoriteAuthors)
	authenticated.Get("/authors/:author/favorite", storyteller.AuthorFavoriteStatus)
	authenticated.Post("/authors/:author/favorite", storyteller.CreateAuthorFavorite)
	authenticated.Delete("/authors/:author/favorite", storyteller.DeleteAuthorFavorite)
	authenticated.Get("/projects/:project", storyteller.Project)
	authenticated.Put("/projects/:project", storyteller.UpdateProject)
	authenticated.Delete("/projects/:project", storyteller.DeleteProject)
	authenticated.Get("/projects/:project/favorite", storyteller.FavoriteStatus)
	authenticated.Post("/projects/:project/favorite", storyteller.CreateFavorite)
	authenticated.Delete("/projects/:project/favorite", storyteller.DeleteFavorite)
	authenticated.Patch("/favorites/projects/:project/visibility", storyteller.SetFavoriteProjectVisibility)
	authenticated.Patch("/favorites/authors/:author/visibility", storyteller.SetFavoriteAuthorVisibility)
	authenticated.Get("/projects/:project/ranking", storyteller.RankingStatus)
	authenticated.Put("/projects/:project/ranking", storyteller.SaveRanking)
	authenticated.Delete("/projects/:project/ranking", storyteller.DeleteRanking)
	authenticated.Get("/story/:project/bookmarks", storyteller.ProjectStoryBookmarks)
	authenticated.Get("/story/:project/stories/:story/bookmarks", storyteller.StoryBookmarks)
	authenticated.Post("/story/:project/stories/:story/bookmarks", storyteller.CreateStoryBookmark)
	authenticated.Delete("/story/:project/stories/:story/bookmarks", storyteller.DeleteStoryBookmark)

	authenticated.Get("/provider-apikeys", storyteller.ProviderAPIKeys)
	authenticated.Post("/provider-apikeys", storyteller.CreateProviderAPIKey)
	authenticated.Put("/provider-apikeys/:apikey", storyteller.UpdateProviderAPIKey)
	authenticated.Delete("/provider-apikeys/:apikey", storyteller.DeleteProviderAPIKey)
	authenticated.Get("/provider-apikeys/:apikey/models", storyteller.ProviderAPIKeyModels)
	authenticated.Post("/provider-apikeys/:apikey/models", storyteller.CreateProviderAPIKeyModel)
	authenticated.Delete("/provider-apikeys/:apikey/models/:model", storyteller.DeleteProviderAPIKeyModel)
	authenticated.Post("/provider-apikeys/:apikey/test-connection", storyteller.TestProviderAPIKey)

	authenticated.Get("/personal-access-tokens", storyteller.PersonalAccessTokens)
	authenticated.Post("/personal-access-tokens", storyteller.CreatePersonalAccessToken)
	authenticated.Delete("/personal-access-tokens/:token", storyteller.DeletePersonalAccessToken)

	authenticated.Get("/usage/summary", storyteller.AgentUsageSummary)
	authenticated.Get("/usage/logs", storyteller.AgentUsageLogs)

	authenticated.Get("/agents", storyteller.Agents)
	authenticated.Get("/agents/provider-models", storyteller.AgentProviderModels)
	authenticated.Post("/agents", storyteller.CreateAgent)
	authenticated.Get("/agents/:agent", storyteller.Agent)
	authenticated.Get("/agents/:agent/versions", storyteller.AgentPromptVersions)
	authenticated.Get("/agents/:agent/versions/:version", storyteller.AgentPromptVersion)
	authenticated.Put("/agents/:agent", storyteller.UpdateAgent)
	authenticated.Delete("/agents/:agent", storyteller.DeleteAgent)

	authenticated.Get("/projects/:project/stories", storyteller.Stories)
	authenticated.Post("/projects/:project/stories", storyteller.CreateStory)
	authenticated.Get("/projects/:project/stories/:story", storyteller.Story)
	authenticated.Put("/projects/:project/stories/:story", storyteller.UpdateStory)
	authenticated.Delete("/projects/:project/stories/:story", storyteller.DeleteStory)
	authenticated.Post("/projects/:project/stories/:story/agents/:agent/run", storyteller.RunAgent)
	authenticated.Post("/projects/:project/stories/:story/agents/:agent/agentic-query", storyteller.RunStoryAgenticQuery)
	authenticated.Get("/projects/:project/stories/:story/agentic-query/:chat", storyteller.StoryAgenticChat)
	authenticated.Post("/projects/:project/stories/:story/agents/:agent/agentic-query/:chat/resend", storyteller.ResendStoryAgenticQuery)
	authenticated.Get("/projects/:project/stories/:story/chat-messages/:message/reference-content", storyteller.StoryChatMessageReferenceContent)
	authenticated.Get("/projects/:project/agentic-proposals/:proposal/reference-content", storyteller.AgentProposalReferenceContent)
	authenticated.Post("/projects/:project/agentic-proposals/:proposal/apply", storyteller.ApplyAgentProposal)
	authenticated.Post("/projects/:project/agentic-proposals/:proposal/mark-applied", storyteller.MarkAgentProposalApplied)
	authenticated.Post("/projects/:project/agentic-proposals/:proposal/reset", storyteller.ResetAgentProposal)
	authenticated.Post("/projects/:project/agentic-proposals/:proposal/reject", storyteller.RejectAgentProposal)
	authenticated.Get("/projects/:project/stories/:story/chat-messages", storyteller.StoryChatMessages)
	authenticated.Get("/projects/:project/stories/:story/versions", storyteller.StoryVersions)
	authenticated.Get("/projects/:project/stories/:story/versions/:version", storyteller.StoryVersion)
	authenticated.Post("/projects/:project/stories/:story/versions/:version/revert", storyteller.RevertStoryVersion)
	authenticated.Get("/projects/:project/stories/:story/image-pages", storyteller.ImageStoryPages)
	authenticated.Get("/projects/:project/stories/:story/bookmarks", storyteller.StoryWritingBookmarks)
	authenticated.Post("/projects/:project/stories/:story/bookmarks", storyteller.CreateStoryWritingBookmark)
	authenticated.Put("/projects/:project/stories/:story/bookmarks", storyteller.UpdateStoryWritingBookmark)
	authenticated.Delete("/projects/:project/stories/:story/bookmarks", storyteller.DeleteStoryWritingBookmark)

	authenticated.Get("/projects/:project/volumes", storyteller.Volumes)
	authenticated.Post("/projects/:project/volumes", storyteller.CreateVolume)
	authenticated.Put("/projects/:project/volumes/:volume", storyteller.UpdateVolume)
	authenticated.Get("/projects/:project/volumes/:volume/activity", storyteller.VolumeActivity)
	// 冊本身也是一筆 story，刪除沿用既有的 DELETE /projects/:project/stories/:story，
	// 非空檢查在 Service.DeleteStory 裡做，不需要另外開一條刪除路由。

	authenticated.Post("/projects/:project/image-pages/presign", storyteller.PresignImageUpload)

	authenticated.Get("/projects/:project/assets", storyteller.Assets)
	authenticated.Post("/projects/:project/assets/presign", storyteller.PresignAssetUpload)
	authenticated.Post("/projects/:project/assets/confirm", storyteller.ConfirmAssetUpload)
	authenticated.Get("/projects/:project/asset-collections", storyteller.AssetCollections)
	authenticated.Post("/projects/:project/asset-collections", storyteller.CreateAssetCollection)
	authenticated.Put("/projects/:project/asset-collections/:collection", storyteller.UpdateAssetCollection)
	authenticated.Delete("/projects/:project/asset-collections/:collection", storyteller.DeleteAssetCollection)
	authenticated.Get("/projects/:project/assets/:asset", storyteller.Asset)
	authenticated.Post("/projects/:project/assets/:asset/replace/presign", storyteller.PresignAssetReplace)
	authenticated.Post("/projects/:project/assets/:asset/replace/confirm", storyteller.ConfirmAssetReplace)
	authenticated.Put("/projects/:project/assets/:asset", storyteller.UpdateAsset)
	authenticated.Put("/projects/:project/assets/:asset/move", storyteller.MoveAsset)
	authenticated.Delete("/projects/:project/assets/:asset", storyteller.DeleteAsset)

	authenticated.Get("/projects/:project/lores", storyteller.Lores)
	authenticated.Get("/projects/:project/lores/page", storyteller.LoresPage)
	authenticated.Get("/projects/:project/lore-collections", storyteller.LoreCollections)
	authenticated.Post("/projects/:project/lore-collections", storyteller.CreateLoreCollection)
	authenticated.Put("/projects/:project/lore-collections/:collection", storyteller.UpdateLoreCollection)
	authenticated.Delete("/projects/:project/lore-collections/:collection", storyteller.DeleteLoreCollection)
	authenticated.Post("/projects/:project/lores", storyteller.CreateLore)
	authenticated.Get("/projects/:project/lores/:lore", storyteller.Lore)
	authenticated.Put("/projects/:project/lores/:lore", storyteller.UpdateLore)
	authenticated.Put("/projects/:project/lores/:lore/move", storyteller.MoveLore)
	authenticated.Delete("/projects/:project/lores/:lore", storyteller.DeleteLore)
	authenticated.Post("/projects/:project/lores/:lore/agents/:agent/run", storyteller.RunLoreAgent)
	authenticated.Post("/projects/:project/lores/:lore/agents/:agent/agentic-query", storyteller.RunLoreAgenticQuery)
	authenticated.Get("/projects/:project/lores/:lore/agentic-query/:chat", storyteller.LoreAgenticChat)
	authenticated.Post("/projects/:project/lores/:lore/agents/:agent/agentic-query/:chat/resend", storyteller.ResendLoreAgenticQuery)
	authenticated.Get("/projects/:project/lores/:lore/chat-messages/:message/reference-content", storyteller.LoreChatMessageReferenceContent)
	authenticated.Get("/projects/:project/lores/:lore/chat-messages", storyteller.LoreChatMessages)
	authenticated.Get("/projects/:project/lores/:lore/versions", storyteller.LoreVersions)
	authenticated.Get("/projects/:project/lores/:lore/versions/:version", storyteller.LoreVersion)
	authenticated.Post("/projects/:project/lores/:lore/versions/:version/revert", storyteller.RevertLoreVersion)
	authenticated.Get("/projects/:project/lores/:lore/bookmarks", storyteller.LoreWritingBookmarks)
	authenticated.Post("/projects/:project/lores/:lore/bookmarks", storyteller.CreateLoreWritingBookmark)
	authenticated.Put("/projects/:project/lores/:lore/bookmarks", storyteller.UpdateLoreWritingBookmark)
	authenticated.Delete("/projects/:project/lores/:lore/bookmarks", storyteller.DeleteLoreWritingBookmark)
}
