package route

import (
	"faryne.dev/controller/storyteller"
	"faryne.dev/middleware/authsession"
	"github.com/gofiber/fiber/v3"
)

func Storyteller(app *fiber.App) {
	group := app.Group("/storyteller")
	group.Get("/projects/public", storyteller.PublicProjects)
	group.Get("/user/:username", storyteller.PublicUserProjects)
	group.Get("/user/:username/favorites/projects", storyteller.PublicFavoriteProjects)
	group.Get("/user/:username/favorites/authors", storyteller.PublicFavoriteAuthors)
	group.Get("/story/share/:token", storyteller.SharedProject)
	group.Get("/story/:project", storyteller.PublicProject)
	group.Get("/story/:project/stories/:story/latest-version", storyteller.PublicStoryLatestVersion)
	group.Get("/story/:project/stories/:story/versions", storyteller.PublicStoryVersions)

	authenticated := group.Group("", authsession.New())
	authenticated.Get("/user", storyteller.UserProfile)
	authenticated.Post("/user", storyteller.SaveUserProfile)
	authenticated.Put("/user", storyteller.SaveUserProfile)
	authenticated.Delete("/user", storyteller.DeleteUserProfile)
	authenticated.Get("/projects", storyteller.Projects)
	authenticated.Post("/projects", storyteller.CreateProject)
	authenticated.Get("/favorites", storyteller.FavoriteProjects)
	authenticated.Get("/favorites/authors", storyteller.FavoriteAuthors)
	authenticated.Get("/authors/:author/favorite", storyteller.AuthorFavoriteStatus)
	authenticated.Post("/authors/:author/favorite", storyteller.CreateAuthorFavorite)
	authenticated.Delete("/authors/:author/favorite", storyteller.DeleteAuthorFavorite)
	authenticated.Get("/projects/:project", storyteller.Project)
	authenticated.Put("/projects/:project", storyteller.UpdateProject)
	authenticated.Delete("/projects/:project", storyteller.DeleteProject)
	authenticated.Get("/projects/:project/favorite", storyteller.FavoriteStatus)
	authenticated.Post("/projects/:project/favorite", storyteller.CreateFavorite)
	authenticated.Delete("/projects/:project/favorite", storyteller.DeleteFavorite)
	authenticated.Patch("/favorites/projects/:project/visibility", storyteller.SetFavoriteProjectVisibility)
	authenticated.Patch("/favorites/authors/:author/visibility", storyteller.SetFavoriteAuthorVisibility)
	authenticated.Get("/projects/:project/ranking", storyteller.RankingStatus)
	authenticated.Put("/projects/:project/ranking", storyteller.SaveRanking)
	authenticated.Delete("/projects/:project/ranking", storyteller.DeleteRanking)
	authenticated.Get("/story/:project/bookmarks", storyteller.ProjectStoryBookmarks)
	authenticated.Get("/story/:project/stories/:story/bookmarks", storyteller.StoryBookmarks)
	authenticated.Post("/story/:project/stories/:story/bookmarks", storyteller.CreateStoryBookmark)
	authenticated.Delete("/story/:project/stories/:story/bookmarks", storyteller.DeleteStoryBookmark)

	authenticated.Get("/provider-apikeys", storyteller.ProviderAPIKeys)
	authenticated.Post("/provider-apikeys", storyteller.CreateProviderAPIKey)
	authenticated.Put("/provider-apikeys/:apikey", storyteller.UpdateProviderAPIKey)
	authenticated.Delete("/provider-apikeys/:apikey", storyteller.DeleteProviderAPIKey)
	authenticated.Post("/provider-apikeys/:apikey/test-connection", storyteller.TestProviderAPIKey)

	authenticated.Get("/personal-access-tokens", storyteller.PersonalAccessTokens)
	authenticated.Post("/personal-access-tokens", storyteller.CreatePersonalAccessToken)
	authenticated.Delete("/personal-access-tokens/:token", storyteller.DeletePersonalAccessToken)

	authenticated.Get("/usage/summary", storyteller.AgentUsageSummary)
	authenticated.Get("/usage/logs", storyteller.AgentUsageLogs)

	authenticated.Get("/agents", storyteller.Agents)
	authenticated.Get("/agents/provider-models", storyteller.AgentProviderModels)
	authenticated.Post("/agents", storyteller.CreateAgent)
	authenticated.Get("/agents/:agent", storyteller.Agent)
	authenticated.Get("/agents/:agent/versions", storyteller.AgentPromptVersions)
	authenticated.Get("/agents/:agent/versions/:version", storyteller.AgentPromptVersion)
	authenticated.Put("/agents/:agent", storyteller.UpdateAgent)
	authenticated.Delete("/agents/:agent", storyteller.DeleteAgent)

	authenticated.Get("/projects/:project/stories", storyteller.Stories)
	authenticated.Post("/projects/:project/stories", storyteller.CreateStory)
	authenticated.Get("/projects/:project/stories/:story", storyteller.Story)
	authenticated.Put("/projects/:project/stories/:story", storyteller.UpdateStory)
	authenticated.Delete("/projects/:project/stories/:story", storyteller.DeleteStory)
	authenticated.Post("/projects/:project/stories/:story/agents/:agent/run", storyteller.RunAgent)
	authenticated.Get("/projects/:project/stories/:story/chat-messages", storyteller.StoryChatMessages)
	authenticated.Get("/projects/:project/stories/:story/versions", storyteller.StoryVersions)
	authenticated.Get("/projects/:project/stories/:story/versions/:version", storyteller.StoryVersion)
	authenticated.Post("/projects/:project/stories/:story/versions/:version/revert", storyteller.RevertStoryVersion)

	authenticated.Get("/projects/:project/lores", storyteller.Lores)
	authenticated.Post("/projects/:project/lores", storyteller.CreateLore)
	authenticated.Get("/projects/:project/lores/:lore", storyteller.Lore)
	authenticated.Put("/projects/:project/lores/:lore", storyteller.UpdateLore)
	authenticated.Delete("/projects/:project/lores/:lore", storyteller.DeleteLore)
	authenticated.Post("/projects/:project/lores/:lore/agents/:agent/run", storyteller.RunLoreAgent)
	authenticated.Get("/projects/:project/lores/:lore/chat-messages", storyteller.LoreChatMessages)
	authenticated.Get("/projects/:project/lores/:lore/versions", storyteller.LoreVersions)
	authenticated.Get("/projects/:project/lores/:lore/versions/:version", storyteller.LoreVersion)
	authenticated.Post("/projects/:project/lores/:lore/versions/:version/revert", storyteller.RevertLoreVersion)
}
